### ISSUE TITLE
Executable file missing from copied framework

### ISSUE THREAD

**Issue by lapcat** [nakiostudio/TwitterX#2]
This is an awesome project, thanks so much!

When using Xcode 9.2 to build, I'm seeing an issue where the executable file is missing from TwitterX framework after Xcode copies it into LauncherX/Contents/Resources, even though the executable is present in the framework built product.

I was able to fix this myself by copying the framework into LauncherX/Contents/Frameworks instead, and changing the twitterXFrameworkURL to point there.

**Comment by nakiostudio** [comment]
Hi @lapcat 👋 

Thanks for reporting. Could you please post the logs of that build?

**Comment by lapcat** [comment]
I discovered that it only happens with the Debug build configuration, not Release configuration.

By trial and error, I found that the SWIFT_OPTIMIZATION_LEVEL build setting is what makes the difference, which is very bizarre. This may be an Xcode bug.
