### ISSUE TITLE
Place to add consumer key and consumer secret?

### ISSUE THREAD

**Issue by thektan** [nakiostudio/TwitterX#5]
I was wondering where the consumer key and secret would need to be added to? And would the LauncherX.app need to be rebuilt after it has been added?

Unfamiliar with macOS apps, but I'm super appreciative and eager to use this! Thanks in advance!

**Comment by nakiostudio** [comment]
Hi @thektan 👋 

You just need to launch Twitter through LauncherX and set the pair of keys on the Preferences menu (shortcut `⌘,`). After that, sign out and sign in again with your user account :)

**Comment by thektan** [comment]
Hmm, for some reason the preferences menu won't appear when I'm in the login screen. 😢

**Comment by nakiostudio** [comment]
I'm not very proud of the workaround I implemented but now you should be able to access the preferences menu.

[LauncherX 0.2.2](https://github.com/nakiostudio/TwitterX/releases/tag/0.2.2)

**Comment by thektan** [comment]
Really sorry for constantly coming back to you with issues, but I immensely appreciate the work you've done on this and the quick fixes you've been able to produce!

I have my OAuth app permissions set to `Read, write, and direct messages`, entered in the pair of keys, and now I'm getting `Client is not permitted to perform this action`.
![screenshot 2018-03-30 10 17 08](https://user-images.githubusercontent.com/4496722/38146611-96f04508-3403-11e8-9d3c-28970f6cb73c.png)

**Comment by nakiostudio** [comment]
Unfortunately developer keys aren't valid.

As I mention in the README of the project:

> Using custom keys implies uncertain consequences, use TwitterX at your own risk.

Hope this helps :)

**Comment by thektan** [comment]
Ah got it! Thanks for your help! 👍Closing this now! 🎉
